language: c
sudo: true
install: sudo apt-get install check
compiler:
  - clang
  - gcc

before_script:
  - cmake --version
  - cmake CMakeLists.txt
  - cmake .

script:
  - make
  - clang --coverage -O0 test_main.c -o test
  - ./test
  - gcov test.c