language: c
sudo: true
install: sudo apt-get install check

compiler:
  - clang
  - gcc

before_script:
  - cmake --version
  - cmake CMakeLists.txt
  - cmake .

script:
  - gcc -g -fprofile-arcs -ftest-coverage test_main.c -o test `pkg-config --cflags --libs check`
  - ./test
  - gcov -b -o test.c